tmp_dir: "/work/$USER/tmp"
dada_root: "/data/project/metaamp/TOOLS/dada_pipe"
dada_src: "../dada_scripts"
dada_lib: "/data/project/metaamp/TOOLS/dada_pipe/dada_env/lib"
raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
do_primers: true
do_dada: true
skip_db: false
do_taxonomy: true
do_postprocessing: true
primers:
  fwd: 
    sequence: GTGYCAGCMGCCGCGGTAA
    name: 515F
  rvs: 
    sequence: GGACTACNVGGGTWTCTAAT
    name: 806R
sequencing_direction: "fwd_1"
primer_cutting:
  overlap: 10
  count: 2
  match: both
  perc_mismatch: 0.2
filtering:
  trunc_length:
    fwd: 0
    rvs: 0
  trunc_qual: 25
  max_EE:
    fwd: 2
    rvs: 2
  minLen:
    fwd: 200
    rvs: 100
  maxLen:
    fwd: Inf
    rvs: Inf
  minQ:
    fwd: 0
    rvs: 0
error_seed: 100
pair_merging:
  min_overlap: 12
  max_mismatch: 0
  just_concatenate: false
  trim_overhang: true
chimeras:
  remove: true
  method: consensus
outputdir: "/data/project/metaamp/PLAYGROUND"
taxonomy:
  db_path: "/data/project/metaamp/DBs/decipher"
  tax_db: "GTDB_r86-mod_September2018"
  threshold: 60
  strand: bottom
  bootstraps: 100
  look_for_species: false
  seed: 100
  target_taxa: .
