raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
primers:
  fwd: 
    sequence: GTGYCAGCMGCCGCGGTAA
    name: 515F
  rvs: 
    sequence: GGACTACNVGGGTWTCTAAT
    name: 806R
paired: true
sequencing_direction: "unknown"
filtering:
  trunc_length:
    fwd: 0
    rvs: 0
  trunc_qual: 11
  max_EE:
    fwd: 5
    rvs: 5
  minLen:
    fwd: 180
    rvs: 100
  maxLen:
    fwd: Inf
    rvs: Inf
  minQ:
    fwd: 0
    rvs: 0
outputdir: "/data/project/metaamp/PLAYGROUND"
taxonomy:
  decipher:
    do: true
    db_path: "/data/project/metaamp/DBs/decipher"
    tax_db: "SILVA_SSU_r132_March2018.RData"
    strand: top
    look_for_species: true
    spec_db: "/data/project/metaamp/DBs/decipher/silva_species_assignment_v132.fa.gz"
  mothur:
    do: true
    db_path: "/data/project/metaamp/DBs/amplicon"
    tax_db: "ifoh_515f.iroh_806r.silva_132"
blast:
  do: true
hand_off:
  biom: true
  phyloseq: true
final_table_filtering:
  do: true
  keep_target_taxa: "."
  target_min_length: 250
  target_max_length: 265
postprocessing:
  rarefaction_curve: true
  funguild:
    do: false
  treeing:
    do: true
