email: ""
tmp_dir: "tmp"
raw_directory: "testdata"
sample_table: "testdata/samples.small.tsv"
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
primers:
  fwd: 
    sequence: GTGYCAGCMGCCGCGGTAA
    name: 515F
  rvs: 
    sequence: GGACTACNVGGGTWTCTAAT
    name: 806R
paired: true
sequencing_direction: "unknown"
primer_cutting:
  overlap: 10
  count: 2
  filter_if_not_match: any
  perc_mismatch: 0.2
  indels: "--no-indels"
  both_primers_in_read: false
filtering:
  trunc_length:
    fwd: 170
    rvs: 130
  trunc_qual: 13
  max_EE:
    fwd: 0.2
    rvs: 0.2
  minLen:
    fwd: 0
    rvs: 0
  maxLen:
    fwd: Inf
    rvs: Inf
  minQ:
    fwd: 0
    rvs: 0
  maxN: 0
  rm_phix: true
error_seed: 100
dada:
  band_size: 16
  homopolymer_gap_penalty: NULL
  pool: false
  omega_A: 1e-40
  priors: ""
  omega_P: 1e-4
  omega_C: 1e-40
  gapless: true
  selfConsist: false
  no_error_assumptions: false
  kdist_cutoff: 0.42
  match: 4
  mismatch: -5
  gap_penalty: -8
  errorEstimationFunction: loessErrfun
pair_merging:
  min_overlap: 12
  max_mismatch: 0
  just_concatenate: false
  trim_overhang: true
chimeras:
  remove: true
  method: consensus
  minFoldParentOverAbundance: 2
  minParentAbundance: 8
  allowOneOff: false
  minOneOffParentDistance: 4
  maxShift: 16
outputdir: "dadasnake_output"
taxonomy:
  decipher:
    do: false
    post_ITSx: false
    db_path: "/data/project/metaamp/DBs/decipher"
    tax_db: "SILVA_SSU_r132_March2018.RData"
    threshold: 60
    strand: top
    bootstraps: 100
    seed: 100  
    look_for_species: false
    spec_db: "/data/project/metaamp/DBs/decipher/silva_species_assignment_v132.fa.gz"
  mothur:
    do: true
    post_ITSx: false
    db_path: "/data/project/metaamp/DBs/amplicon2020"
    tax_db: "SILVA_138_SSURef_NR99_prok.515F.806R"
    cutoff: 60
blast:
  do: false
  db_path: "/data/db/ncbi/blast/db/nt/2018-09-07"
  tax_db: nt
  e_val: 0.01
  tax2id: ""
  all: false
ITSx:
  do: false
  min_regions: 1
  region: ITS2
  e_val: 1e-5
hand_off:
  biom: true
  phyloseq: false
final_table_filtering:
  do: true
  keep_target_taxa: "."
  target_min_length: 245
  target_max_length: 275
postprocessing:
  rarefaction_curve: true
  funguild:
    do: false
    funguild_db: "/data/project/metaamp/DBs/amplicon/funguild_db.json"
    classifier: mothur
  treeing:
    do: true
    fasttreeMP: "module load libgomp/4.4.7\nexport OMP_NUM_THREADS={threads}\n/data/project/metaamp/TOOLS/FastTreeMP"
