email: ""
raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
outputdir: "/work/$USER/AMF_output"
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
taxonomy:
  decipher:
    do: false
  mothur:
    do: true
    db_path: "../DBs/amplicon"
    tax_db: "SILVA_138_SSURef_NR99_euk.NS31.AML2"
primers:
  fwd: 
    sequence: TTGGAGGGCAAGTCTGGTGCC
    name: NS31
  rvs: 
    sequence: GAACCCAAACACTTTGGTTTCC
    name: AML2
paired: true
sequencing_direction: "unknown"
filtering:
  trunc_length:
    fwd: 0
    rvs: 0
  trunc_qual: 7
  max_EE:
    fwd: 2
    rvs: 2
  minLen:
    fwd: 260
    rvs: 210
  maxLen:
    fwd: Inf
    rvs: Inf
  minQ:
    fwd: 0
    rvs: 0
blast:
  do: false
hand_off:
  biom: true
  phyloseq: false
final_table_filtering:
  do: true
  keep_target_taxa: "Glomeromycotina"
postprocessing:
  rarefaction_curve: true
  funguild:
    do: false
  treeing:
    do: true
