email: ""
raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
outputdir: "/work/$USER/454_output"
taxonomy:
  decipher:
    do: false
  mothur:
    do: true
    db_path: "../DBs/amplicon"
    tax_db: "SILVA_138_SSURef_NR99_prok"
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
primers:
  fwd: 
    sequence: CTGCTGCCTCCCCGTAGG
    name: 357F
  rvs: 
    sequence: CCGTCAATTCMTTTRAGN
    name: 926R
paired: false
sequencing_direction: "rvs_1"
filtering:
  trunc_length:
    fwd: 350
    rvs: 350
  trunc_qual: 5
  max_EE:
    fwd: 2
  maxLen:
    fwd: Inf
  minQ:
    fwd: 0
chimeras:
  remove: true
  method: pooled
dada:
  pool: true
  band_size: 32
  homopolymer_gap_penalty: -1
  omega_C: 0
  omega_A: 1e-250
  gapless: false
blast:
  do: false
hand_off:
  biom: true
  phyloseq: false
final_table_filtering:
  do: false
postprocessing:
  rarefaction_curve: true
  funguild:
    do: false
  treeing:
    do: true
