email: ""
raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
primers:
  fwd: 
    sequence: TTGGAGGGCAAGTCTGGTGCC
    name: NS31
  rvs: 
    sequence: GAACCCAAACACTTTGGTTTCC
    name: AML2
paired: true
sequencing_direction: "unknown"
filtering:
  trunc_length:
    fwd: 0
    rvs: 0
  trunc_qual: 20
  max_EE:
    fwd: 2
    rvs: 2
  minLen:
    fwd: 200
    rvs: 100
  maxLen:
    fwd: Inf
    rvs: Inf
  minQ:
    fwd: 0
    rvs: 0
outputdir: "AMF_output"
taxonomy:
  decipher:
    do: false
  mothur:
    do: true
    db_path: "/work/$USER/DBs/amplicon"
    tax_db: "SILVA_138_SSURef_NR99_euk.NS31.AML2"
blast:
  do: false
  db_path: "/work/$USER/DBs/amplicon"
  tax_db: "MaarjAM_vt_types.20150204.format.fasta"
  tax2id: ""
hand_off:
  biom: true
  phyloseq: false
final_table_filtering:
  do: true
  keep_target_taxa: "Glomeromycotina"
postprocessing:
  rarefaction_curve: true
  funguild:
    do: false
  treeing:
    do: true
