email: ""
raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
outputdir: "/work/$USER/output16S_pacbio"
taxonomy:
  mothur:
    do: true
    db_path: "../DBs/amplicon"
    tax_db: "SILVA_138_SSURef_NR99_prok"
  decipher:
    do: false
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
primers:
  fwd:
    sequence: AGRGTTYGATYMTGGCTCAG
    name: 27F
  rvs:
    sequence: RGYTACCTTGTTACGACTT
    name: 1492R
paired: false
sequencing_direction: "unknown"
primer_cutting:
  overlap: 12
  perc_mismatch: 0.2
  indels: ''
  count: 2
  both_primers_in_read: true
filtering:
  trunc_length:
    fwd: 0
  trunc_qual: 
    fwd: 0
  max_EE:
    fwd: 2
  minLen:
    fwd: 1000
  maxLen:
    fwd: 1600
  minQ:
    fwd: 3
  rm_phix: false
dada:
  pool: true
  band_size: 32
  homopolymer_gap_penalty: -1
  errorEstimationFunction: PacBioErrfun
chimeras:
  remove: true
  method: consensus
  minFoldParentOverAbundance: 3.5
final_table_filtering:
  do: true
  keep_target_taxa: "Bacteria"
  target_min_length: 0
  target_max_length: Inf
blast:
  do: false
hand_off:
  biom: true
  phyloseq: false
postprocessing:
  rarefaction_curve: true
  funguild:
    do: false
  treeing:
    do: true
