raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
outputdir: "/work/$USER/output16S_nanoporeChopseq"
do_dada: true
do_primers: true
do_taxonomy: true
paired: false
primer_cutting:
  overlap: 12
  perc_mismatch: 0.25
  indels: ''
  count: 1
  both_primers_in_read: true
primers:
  fwd:
    sequence: AGRGTTTGATCMTGGCTCAG
    name: 8F
  rvs:
    sequence: GGGCGGWGTGTACAAG
    name: 1387R
sequencing_direction: fwd_1
filtering:
  trunc_length:
    fwd: 0
  trunc_qual: 
    fwd: 0
  max_EE:
    fwd: Inf
  minLen:
    fwd: 1000
  maxLen:
    fwd: Inf
  minQ:
    fwd: 0
dada:
  pool: true
  band_size: 32
  homopolymer_gap_penalty: -1
  use_quals: false
  omega_C: 1
  omega_A: 1e-30
  gapless: false
  no_error_assumptions: false
  errorEstimationFunction: noqualErrfun
  selfConsist: false
chimeras:
  remove: true
  method: pooled
  minFoldParentOverAbundance: 3.5
final_table_filtering:
  do: false
postprocessing:
  funguild:
    do: false
  rarefaction_curve: true
  treeing:
    do: false
ITSx:
  run: false
taxonomy:
  decipher:
    do: false
  mothur:
    cutoff: 60
    db_path: "../DBs/amplicon"
    tax_db: "SILVA_138_SSURef_NR99_prok"
    do: true
    post_ITSx: false
tmp_dir: /work/$USER/tmp
email: ''
