email: ""
raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
outputdir: "/work/$USER/AMF_single_output"
taxonomy:
  decipher:
    do: false
  mothur:
    do: true
    db_path: "../DBs/amplicon"
    tax_db: "SILVA_138_SSURef_NR99_euk.NS31.AML2"
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
primers:
  fwd: 
    sequence: TTGGAGGGCAAGTCTGGTGCC
    name: NS31
  rvs: 
    sequence: GAACCCAAACACTTTGGTTTCC
    name: AML2
paired: false
sequencing_direction: "fwd_1"
filtering:
  trunc_length:
    fwd: 250
  trunc_qual: 
    fwd: 13
  max_EE:
    fwd: 0.2
  maxLen:
    fwd: Inf
  minQ:
    fwd: 0
blast:
  do: false
hand_off:
  biom: true
  phyloseq: false
final_table_filtering:
  do: true
  keep_target_taxa: "Glomeromycotina"
postprocessing:
  rarefaction_curve: true
  funguild:
    do: false
  treeing:
    do: true
