__default__: 
  call: "qsub -cwd"
  mem_per_cpu: "-l h_vmem=8G"
  partition: ""
  runtime: "-l h_rt="
  threads: "-pe smp "

dada_mergeSamples:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

dada_dadaPairs_pool:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

dada_dadaSingle_pool:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

dada_mergeruns:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

nochime_numbers:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

tabled_numbers:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

mothur_taxonomy:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

blastn:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

rarefaction_curve_noFilter:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

treeing_noFilter_fasttreeMP:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

taxonomy_to_OTUtab:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

prepare_blastn:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

biom_handoff_preTax:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"

biom_handoff_tax:
  partition: "-l highmem"
  mem_per_cpu: "-l h_vmem=30G"



