$schema: "http://json-schema.org/draft-07/schema#"

description: DADA2 pipeline Snakemake configuration file

type: object

properties:
  tmp_dir:
    type: string 
  dada_root:
    type: string
  dada_src:
    type: string
  dada_lib:
    type: string 
  do_primers: 
    type: boolean
  do_dada:
    type: boolean 
  skip_db: 
    type: boolean 
  do_taxonomy: 
    type: boolean
  do_postprocessing:
    type: boolean 
  remove_chimeras: 
    type: boolean 
  primers: 
    type: object
    properties:
      fwd:
        type: object
        properties: 
          name: 
            type: string
          sequence:  
            type: string
            pattern: "^[GATCRYSWKMBDHVNgatcryswkmbdhvn]{10,30}$"
      rvs: 
        type: object
        properties:
          name:
            type: string
          sequence:
            type: string
            pattern: "^[GATCRYSWKMBDHVNgatcryswkmbdhvn]{10,30}$"
  sequencing_direction:
    type: string
    enum:
      - "fwd_1"
      - "rvs_1"
      - mixed
      - unknown
  primer_cutting:
    type: object
    properties:
      overlap:
        type: number
        maximum: 30
      count:
        type: number
      match: 
        type: string
        enum: 
          - both
          - any
          - first
      perc_mismatch: 
        type: number
        maximum: 1
  trunc_length:
    type: object
    properties: 
      fwd:
        type: number
        minimum: 50
        maximum: 300 
      rvs:
        type: number
        minimum: 50
        maximum: 300
  min_qual:
    type: object
    properties:
      fwd:
        type: number
        minimum: 0
        maximum: 45
      rvs:
        type: number
        minimum: 0
        maximum: 45
  outputdir:
    type: string
    pattern: "^/.+(/.+)*$"
  db_path: 
    type: string
  tax_db:
    type: string   

