ITSx:
  do: false
  e_val: 1e-5
  min_regions: 1
  region: ITS2
blast:
  all: false
  db_path: /data/db/ncbi/blast/db/nt/2018-09-07
  do: false
  e_val: 0.01
  tax2id: ''
  tax_db: nt
chimeras:
  method: consensus
  remove: true
dada:
  band_size: 16
  homopolymer_gap_penalty: null
do_dada: false
do_postprocessing: false
do_primers: true
do_taxonomy: false
email: ''
error_seed: 100
filtering:
  trunc_length:
    fwd: 170
    rvs: 130
  trunc_qual: 9
  max_EE:
    fwd: 0.5
    rvs: 0.5
  minLen:
    fwd: 100
    rvs: 100
  maxLen:
    fwd: Inf
    rvs: Inf
  minQ:
    fwd: 0
    rvs: 0
final_table_filtering:
  do: true
  keep_target_taxa: .
  target_max_length: 265
  target_min_length: 240
hand_off:
  biom: false
  phyloseq: false
outputdir: testoutput
pair_merging:
  just_concatenate: false
  max_mismatch: 0
  min_overlap: 12
  trim_overhang: true
paired: true
postprocessing:
  funguild:
    classifier: mothur
    do: false
    funguild_db: /work/$USER/DBs/amplicon/funguild_db.json
  rarefaction_curve: true
  treeing:
    do: true
    fasttreeMP: ''
primer_cutting:
  count: 2
  filter_if_not_match: any
  indels: --no-indels
  overlap: 10
  perc_mismatch: 0.2
primers:
  fwd:
    sequence: GTGYCAGCMGCCGCGGTAA
    name: 515F
  rvs:
    sequence: GGACTACNVGGGTWTCTAAT
    name: 806R
raw_directory: testdata
sample_table: testdata/samples.small.tsv
sequencing_direction: unknown
sessionName: TEST
taxonomy:
  decipher:
    bootstraps: 100
    db_path: /work/$USER/DBs/decipher
    do: false
    look_for_species: false
    post_ITSx: false
    seed: 100
    spec_db: /work/$USER/DBs/decipher/silva_species_assignment_v132.fa.gz
    strand: top
    tax_db: SILVA_SSU_r132_March2018.RData
    threshold: 60
  mothur:
    cutoff: 60
    db_path: /work/$USER/DBs/amplicon
    do: true
    post_ITSx: false
    tax_db: SILVA_138_SSURef_NR99_prok.515F.806R
tmp_dir: tmp
